[package]
name = "tui_layout"
version = "0.1.0"
edition = "2021"
description = "A TUI management library for paneling and input focus."

[dependencies]
crossterm = "0.25.0"
tui = "0.19.0"

[dev-dependencies]
lazy_static = "1.4.0"
backtrace = "0.3.67"
crossbeam = "0.8.1"
